version: "3"
services:
  hub:
    image: selenium/hub:latest
    ports:
      - 4444:4444
  chrome:
    image: seleniarm/node-chromium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
    - hub
    deploy:
      replicas: 4
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  firefox:
    image: seleniarm/node-firefox
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 4
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
